# Welcome to Jekyll!

# Website settings
title: Jalpc
description: Jack's blog,use Jekyll and github pages.
keywords: Jack,Jalpc,blog,Jekyll,github,gh-pages
baseurl:
url: http://www.ferhatyalcin.com
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog

# author
author:
  name: Jarrekk
  first_name: Ferhat
  last_name: Yalçın
  cv: http://cv.jarrekk.com
  email: ylcnfrht@gmail.com
  facebook_username: jiakunnj
  github_username: ylcnfrht
  linkedin_id: jarrekk
  avatar: /static/assets/img/landing/profile.jpeg
  skill_icon1:
    - name: icon-python
    - name: icon-shell
  skill_icon2:
    - name: icon-mongodb
    - name: icon-docker
  desc:  I am software engineer with 2+ years experience, skilled in Node.JS, Javascript, Restful APIs and noSQL databases such as couchbase, redis, mongoDB and writing scripts experience. passion for learn new technologies.Life is a continuous learning process, so work makes me more rigorous, travel makes my life more colorful. I can make lots of friends when I coding and travel.


# comment
disqus:
  name: jalpc

# analytics
## google analytics
ga:
  id: UA-93473370-1

go:
  id: GTM-NHMS8GD

## growingIO
gio:
  # id: a49d4901c7853da9

## donation
donation: on

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
